loans/urls.py
from django.urls import path
from loans.views import *
from users.views import *

urlpatterns = [
    path('apply-loan/', not_logged_in(apply_loan_index), name='apply_for_loan'),
    path('payments/', not_logged_in(payments_index), name='payments'),
]

mybank/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from bankaccount.views import *
from loans.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # чтобы не писать каждый раз ссылку, то делаем для каждого приложения отдельный файл urls
    path('bankaccount/', include('bankaccount.urls')),
    path('loans/', include('loans.urls')),
    path('users/', include('users.urls')),

    # Первый вариант являктся просто как представление вида и поэтмоу я не смогу передавать параметры и нужно
    # во views.py сделать метод, который и нужен для реализации того что хочу
    # path('', TemplateView.as_view(template_name='Home.html'), name='Home'),
    path('', home_page, name='Home'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Специальный обработчик для 404, handler вызывается каждый раз когда ошибка будет
handler404 = pageNotFound

loans/models.py
import uuid

from django.core.validators import *
from django.db import models
from users.models import Users
from mybank.FernetFile import *

from datetime import datetime, timedelta


class Loans(models.Model):
    Loans_TYPE = (
         ('Consumer_loan', 'Потребительский кредит'),
         ('Mortgage_loan', 'Ипотечный кредит'),
         ('Auto_loan', 'Автокредит'),
    )

    Currency_TYPES_Loans = (
        ('BYN', 'Белорусский рубль'),
        ('USD', 'Американский доллар'),
        ('EUR', 'Евро'),
    )

    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    loan_number = models.CharField(max_length=255, blank=False, null=False, unique=True,
                                      validators=[MinLengthValidator(16)])
    # сумму выдачи, которую пользователь выбрал
    issue_amount = models.DecimalField(max_digits=6, decimal_places=0, blank=False)

    # сумма возврата с процентами
    refund_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    # сколько уже оплатили
    paid = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    # остаток
    remainder = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    # платеж в месяц
    payment_amount_per_month = models.DecimalField(max_digits=8, decimal_places=2, blank=False)
    currency_loan = models.CharField(max_length=3, choices=Currency_TYPES_Loans)
    months = models.IntegerField(null=True)
    date_of_start = models.DateField(auto_now_add=True)
    date_of_end = models.DateField()
    loan_type = models.CharField(max_length=100, choices=Loans_TYPE, null=False)
    destination_account_number = models.CharField(max_length=255, null=True)
    # статус для того, чтобы потом ограничить возможность оплаты суммы кредита, когда он уже закрыт
    status = models.CharField(max_length=15, blank=False, null=False)

    def save(self, *args, **kwargs):
        if not self.loan_number:
            self.loan_number = uuid.uuid4().hex[:16].upper()

        # self.loan_number = fernet_encrypt(self.loan_number)

        super().save(*args, **kwargs)

    # def decrypted_loan_number(self):
    #     return fernet_decrypt(self.loan_number)


class Loan_History(models.Model):
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE)
    loan_number = models.CharField(max_length=20, blank=False, null=False)
    summ_of_payment = models.DecimalField(max_digits=8, decimal_places=2, blank=False)
    remainder = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    currency = models.CharField(max_length=20)
    date_of_payment = models.DateField()
    status = status = models.CharField(max_length=15, blank=False, null=False)

loans/forms.py
from django import forms

from bankaccount.models import BankAccounts
from .models import *


class MakeALoanForm(forms.ModelForm):
    class Meta:
        model = Loans
        fields = ['loan_type', 'months', 'issue_amount', 'currency_loan', 'destination_account_number']

        loan_type = forms.ChoiceField(label='Тип кредита', choices=Loans.Loans_TYPE)
        months = forms.IntegerField(label='Месяцы')
        issue_amount = forms.DecimalField(label="Сумма кредита")
        currency_loan = forms.ChoiceField(label='Валюта кредита', choices=Loans.Currency_TYPES_Loans)

        destination_account_number = forms.ModelChoiceField(
            label='Счет получателя',
            queryset=BankAccounts.objects.none(),
            to_field_name='account_number',
        )

    def __init__(self, *args, user=None, **kwargs):
        super(MakeALoanForm, self).__init__(*args, **kwargs)
        self.fields['destination_account_number'].queryset = BankAccounts.objects.filter(user=user)

loans/views.py
from django.contrib import messages
from datetime import datetime, timedelta

from django.core.mail import send_mail
from django.shortcuts import render, redirect
from decimal import Decimal

from django.utils import timezone

from bankaccount.forms import MoneyTransferForm
from bankaccount.models import BankAccounts
from bankaccount.views import convert_currency
from loans.forms import MakeALoanForm
from loans.models import Loans, Loan_History
from mybank.FernetFile import *

menu = [
    # {'title': 'Личный кабинет', 'url_name': 'account_settings'},
    {'title': 'Просмотр счетов', 'url_name': 'bankaccount'},
    {'title': 'Денежные переводы', 'url_name': 'money_transfer'},
    {'title': 'Оформление кредита', 'url_name': 'apply_for_loan'},
    {'title': 'Платежи', 'url_name': 'payments'},
    {'title': 'История транзакций', 'url_name': 'money_transfer_history'},
]


def apply_loan_index(request):
    if request.method == 'POST':
        form = MakeALoanForm(request.POST, user=request.user)

        if form.is_valid():
            print("Cleaned data:", form.cleaned_data)

            date_of_birth = request.user.documents.date_of_birth
            age = calculate_age(date_of_birth)

            if age < 18:
                messages.error(request, f'Извините, но мы отказываемся вам выдавать кредит в вашем возрасте: {age}')
                return redirect('apply_for_loan')

            loan_type = form.cleaned_data['loan_type']
            months = form.cleaned_data['months']
            issue_amount = form.cleaned_data['issue_amount']
            currency_loan = form.cleaned_data['currency_loan']
            destination_account_number = form.cleaned_data['destination_account_number']
            #destination_account_number_get = fernet_encrypt(str(destination_account_number))
            #messages.error(request, destination_account_number_get)

            existing_loans_count = Loans.objects.filter(user=request.user, status='Оплачивается').count()
            limit = 2

            try:
                destination_account = BankAccounts.objects.get(account_number=destination_account_number,
                                                               user=request.user)
            except BankAccounts.DoesNotExist:
                destination_account = None
                messages.error(request, 'Счет не существует или не принадлежит текущему пользователю!')

            if months < 1 or months > 360:
                messages.error(request, 'Введите значения от 1 месяца до 360 (30 лет)')
            elif issue_amount < 100 or issue_amount > 100000:
                messages.error(request, 'Минимальная сумма кредита: 100 у.е. \nМаксимальная сумма кредита: 100000 у.е.')
            elif currency_loan != destination_account.currency:
                messages.error(request, 'Данный счет не в той же валюте что вы выбрали.')
            elif existing_loans_count == limit:
                messages.error(request, 'Вы достигли лимит оформления кредита, закройте, пожалуйста ваши задолженности.')
            else:
                loan = form.save(commit=False)
                loan.user = request.user
                loan.status = 'Оплачивается'
                loan.paid = 0

                loan.refund_amount = calculated_refund_amount(loan_type, issue_amount, months)
                loan.remainder = loan.refund_amount - loan.paid
                loan.payment_amount_per_month = loan.refund_amount / months
                loan.date_of_start = datetime.now()
                loan.date_of_end = datetime.now() + timedelta(days=30*months)

                destination_account.balance += issue_amount
                destination_account.save()

                loan.save()

                send_email_user_loan(loan.loan_number, loan.currency_loan, loan.status, request.user.email)

                messages.success(request, 'Кредит успешно оформлен!')
                return redirect('apply_for_loan')
        else:
            print("Form errors:", form.errors)
            messages.error(request, 'Вы ввели некорректные данные!')
    else:
        user = request.user
        loans = user.loans_set.all().order_by('-status')
        form = MakeALoanForm(user=request.user)

    context = {
        'title': 'Оформление кредита',
        'menu': menu,
        'loans': loans,
        'form': form

    }
    return render(request, 'loans/Apply_for_a_loan.html', context)


def send_email_user_loan(loan_number, currency, status, email):
    subject = 'MyBank'
    message = (
        f'Информация по кредиту! \n\n'
        f'Уважаемый клиент, мы одобрили вам ваш запрос на кредит!\n'
        f'Ваш номер кредитного счета: {loan_number} {currency}\n'
        f'Статус: {status}\n'
        f'Никому не сообщайте свой номер счета для обеспечения безопасности.\n\n'
        f'Вы можете войти в личный кабинет MyBank и управлять своим счетом.\n'
    )

    send_mail(
        subject,
        message,
        'settings.EMAIL_HOST_USER',
        [email],
        fail_silently=False,
    )


def calculate_age(date_of_birth):
    today = timezone.now().date()
    age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))
    return age


def payments_index(request):
    if request.method == 'POST':
        form = MoneyTransferForm(request.POST, user=request.user)

        if form.is_valid():
            print("Cleaned data:", form.cleaned_data)

            source_account_number = form.cleaned_data['sender_id'].account_number
            destination_account_number = form.cleaned_data['destination_account_number']
            amount = form.cleaned_data['amount']

            # Получение счетов отправителя и получателя
            source_account = BankAccounts.objects.get(account_number=str(source_account_number))
            fromCurrency = source_account.currency

            destination_account = Loans.objects.get(loan_number=destination_account_number)
            toCurrency = destination_account.currency_loan

            converted_amount = convert_currency(amount, toCurrency, fromCurrency)

            if source_account.balance >= amount:
                if 0 < amount <= destination_account.remainder and destination_account.status == 'Оплачивается':

                    source_account.balance -= amount
                    destination_account.paid += converted_amount
                    destination_account.remainder = destination_account.refund_amount - destination_account.paid
                    if destination_account.paid == destination_account.refund_amount:
                        destination_account.status = 'Закрыт'

                    source_account.save()
                    destination_account.save()

                    # Логирование
                    Loan_History.objects.create(
                        loan=destination_account,
                        loan_number=destination_account.loan_number,
                        summ_of_payment=converted_amount,
                        remainder=destination_account.remainder,
                        date_of_payment=datetime.now(),
                        currency=fromCurrency,
                        status=destination_account.status,
                    )

                    messages.success(request, 'Оплата была успешна завершена')
                    return redirect('payments')
                else:
                    messages.error(request, 'Ошибка ввода сумму перевода или неверный счет кредита!')
            else:
                messages.error(request, 'Недостаточно средств для перевода')
        else:
            print("Form errors:", form.errors)
            messages.error(request, 'Вы ввели некорректные данные!')

    else:
        form = MoneyTransferForm(user=request.user)

    context = {
        'title': 'Платежи',
        'menu': menu,
        'form': form,
    }

    return render(request, 'loans/Payments.html', context)


def calculated_refund_amount(loan_type, issue_amount, months):
    if loan_type == 'Consumer_loan':
        return calculated_result(15.25, months, issue_amount)

    if loan_type == 'Mortgage_loan':
        return calculated_result(12.5, months, issue_amount)

    if loan_type == 'Auto_loan':
        return calculated_result(9.5, months, issue_amount)


def calculated_result(procent, months, issue_amount):
    # Чтобы не забыть как считаются проценты годовых
    # Сначала нужно поделить общий процент на 100 и 12, чтобы получить проценты за ежемесячный платеж. То есть какой процент от суммы платежа в месяц
    # Потом уже вычисляем полную сумму добавки к запрашиваемой сумме (То есть это столько пользователь будет должен за определенный период)
    annual_interest_rate = procent / 100
    monthly_interest_rate = (annual_interest_rate / 12)
    total_interest = Decimal(monthly_interest_rate * months) * issue_amount
    total_payment = issue_amount + total_interest
    return total_payment

loans/templates/loans/Apply_for_a_loan.html
{% extends 'user/base_form.html' %}

{% load static %}

{% block content %}

<head>
        <link type="text/css" href="{% static 'loans/css/Apply_for_a_loan.css' %}" rel="stylesheet">
</head>

<header>
        <h1>Оформление кредита</h1>
        <p>Оставляйте запрос для получения кредита, {{ user.username }}!</p>
</header>

<br/>

<div class="container">
        {% if user.is_authenticated %}

        <div class="container__loan-calculator">
                <h2>Кредитный калькулятор</h2>
                <p>Введите параметры кредита, чтобы рассчитать его сумму и ежемесячный платеж:</p>
                <input type="number" id="loanAmount" placeholder="Сумма кредита" min="0" max="100000" oninput="validity.valid||(value='');">
                {% csrf_token %}
                <label for="{{ form.loan_type.id_for_label }}">Тип кредита: </label>
                {{ form.loan_type }}
                <label for="{{ form.currency_loan.id_for_label }}">Валюта: </label>
                {{ form.currency_loan }}
                <input type="number" id="loanTerm" placeholder="Срок кредита в месяцах" min="1" max="360" oninput="validity.valid||(value='360')">
                <button onclick="calculateLoan()">Рассчитать</button>
                <p id="totalPayment">Итоговая сумма платежа: </p>
                <p id="procent">Проценты годовых: </p>
                <p id="monthlyPayment">Ежемесячный платеж: </p>
        </div>

        <div class="container__make-loan">
                <form method="post" action="{% url 'apply_for_loan' %}">
                        {% csrf_token %}
                        <p>Выберите тип кредита:</p>
                        {{ form.loan_type }}
                        <p>Введите на какой срок (месяцев) вы хотите оформить кредит. Минимальный срок - 1 месяц:</p>
                        {{ form.months }}
                        <p>Сумма кредита, который вы запрашиваете (Минимальная сумма - 100.00 у.е. Максимальная сумма - 100 000.00 у.е.):</p>
                        {{ form.issue_amount }}
                        <p>Валюта кредитирования:</p>
                        {{ form.currency_loan }}
                        <p>Напишите номер счета, соответсвующий валюте кредитирования, если у вас нет данного счета, то вам придется его создать!</p>
                        {{ form.destination_account_number }}
                        <br/>
                        <button type="submit" class="apply">Подать на получение кредита</button>
                </form>
        </div>

        <div class="container__list-of-loans">
                <h2>Ваши банковские счета:</h2>
                <table>
                <thead>
                        <tr>
                        <th>Тип счета</th>
                        <th>Номер счета</th>
                        <th>Сумма выдачи</th>
                        <th>Сумма возврата</th>
                        <th>Оплачено</th>
                        <th>Остаток</th>
                        <th>Платеж в месяц</th>
                        <th>Валюта</th>
                        <th>Дата начала</th>
                        <th>Последний срок</th>
                        <th>Кол-во месяцев оплаты</th>
                        <th>Статус</th>
                        </tr>
                </thead>
                <tbody>
                        {% for loan in loans  %}
                        <tr>
                                <td>{{ loan.get_loan_type_display }}</td>
<!--                                <td>{{ loan.decrypted_loan_number }}</td>-->
                                <td>{{ loan.loan_number|slice:":3"|ljust:"12" }}**********{{loan.loan_number|slice:"-3:"}}</td>
                                <td>{{ loan.issue_amount }}</td>
                                <td>{{ loan.refund_amount }}</td>
                                <td>{{ loan.paid }}</td>
                                <td>{{ loan.remainder }}</td>
                                <td>{{ loan.payment_amount_per_month }}</td>
                                <td>{{ loan.currency_loan }}</td>
                                <td>{{ loan.date_of_start }}</td>
                                <td>{{ loan.date_of_end }}</td>
                                <td>{{ loan.months }}</td>
                                <td>{{ loan.status }}</td>
                        </tr>
                        {% endfor %}
                </tbody>
                </table>
        </div>
        {% endif %}

</div>

<script src="{% static 'loans/js/calculateLoan.js' %}"></script>


{% endblock %}

loans/templates/loans/Payments.html
{% extends 'user/base_form.html' %}

{% load static %}

{% block content %}

<head>
        <link type="text/css" href="{% static 'loans/css/Apply_for_a_loan.css' %}" rel="stylesheet">
</head>

<header>
        <h1>Платежи</h1>
        <p>Выполняйте платежи здесь, {{ user.username }}!</p>
        <p>P.S. В данном случае только оплата кредита</p>
</header>

<br/>

<div class="container">
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'payments' %}" class="block__form">
                {% csrf_token %}
                <p>Ваш счет:</p>
                {{ form.sender_id }}
                <p>Счет кредита</p>
                {{ form.destination_account_number }}
                <p>Сумма оплаты:</p>
                {{ form.amount }}
                <button type="submit" >Оплатить</button>
        </form>

        {% endif %}

</div>



{% endblock %}