bankaccount/urls.py
from django.urls import path

from bankaccount import views
from bankaccount.views import *
from users.views import *

urlpatterns = [
    path('bankaccounts/', not_logged_in(bankaccount_index), name='bankaccount'),
    path('money_transfer/', not_logged_in(money_transfer_index), name='money_transfer'),
    # path('money_transfer/', not_logged_in(money_transfer_info), name='money_transfer_info'),
    path('money_transfer_history/', not_logged_in(views.money_transfer_history), name='money_transfer_history'),

    # если будем присваивать для каждой категории отдельный id
    path('categories/<int:categoryID>/', categories),
]

loans/urls.py
from django.urls import path
from loans.views import *
from users.views import *

urlpatterns = [
    path('apply-loan/', not_logged_in(apply_loan_index), name='apply_for_loan'),
    path('payments/', not_logged_in(payments_index), name='payments'),
]

mybank/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from bankaccount.views import *
from loans.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # чтобы не писать каждый раз ссылку, то делаем для каждого приложения отдельный файл urls
    path('bankaccount/', include('bankaccount.urls')),
    path('loans/', include('loans.urls')),
    path('users/', include('users.urls')),

    # Первый вариант являктся просто как представление вида и поэтмоу я не смогу передавать параметры и нужно
    # во views.py сделать метод, который и нужен для реализации того что хочу
    # path('', TemplateView.as_view(template_name='Home.html'), name='Home'),
    path('', home_page, name='Home'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Специальный обработчик для 404, handler вызывается каждый раз когда ошибка будет
handler404 = pageNotFound

bankaccount/models.py
import uuid

from django.core.validators import *
from django.db import models

from mybank import settings
from users.models import Users
from datetime import datetime, timedelta
from cryptography.fernet import Fernet
from mybank import FernetFile


# key = settings.SECRET_KEY
# fernet = Fernet(key)


# Банковский счет
class BankAccounts(models.Model):
    BankAccounts_TYPES = (
        ('checking_account', 'Текущий счет'),
        #('loan_account', 'Кредитный счет'),
    )

    Currency_TYPES = (
        ('BYN', 'Белорусский рубль'),
        ('USD', 'Американский доллар'),
        ('RUB', 'Российский рубль'),
        ('EUR', 'Евро'),
        ('CNY', 'Китайский юань'),
    )

    # Чтобы вывести при ошибке второе значение списка, а не checking_account
    ACCOUNT_TYPES_DICT = dict(BankAccounts_TYPES)
    CURRENCY_TYPES_DICT = dict(Currency_TYPES)

    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=30, choices=BankAccounts_TYPES)
    account_number = models.CharField(max_length=255, blank=False, null=False, unique=True,
                                      validators=[MinLengthValidator(16)])
    balance = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    currency = models.CharField(max_length=3, choices=Currency_TYPES)
    expiration_date = models.DateField()

    def save(self, *args, **kwargs):
        # нужно также сгененрировать (уникальный) номер счета, а то из-за уникальности не добить счетов
        if not self.account_number:
            self.account_number = uuid.uuid4().hex[:16].upper()

        # encrypted_account_number = fernet.encrypt(self.account_number.encode())
        # self.account_number = encrypted_account_number
        # self.account_number = FernetFile.fernet_encrypt(self.account_number)

        # При сохранении объекта, генерируем срок годности
        self.expiration_date = datetime.now() + timedelta(days=365 * 4)
        super().save(*args, **kwargs)

    # def get_decrypted_account_number(self):
    #     return FernetFile.fernet_decrypt(self.account_number)
        #str = 'b\'gAAAAABlbM-mjryZfh5yPs7yws_dzbmD2O0jCl5g0wC5osQi1OOmhPvpRgNTH0rm3aRzk1gle8WiWNFkiDDeLjTY6MLu8kmIx7_pLVWuB7mjbQgLKxUkUW0=\''
        # db_account_number = self.account_number
        # clean_data = eval(db_account_number)
        # decrypted_account_number = fernet.decrypt(clean_data).decode()
        #decrypted_account_number = fernet.decrypt(self.account_number).decode()
        # return decrypted_account_number


    # Вывод счетов текущего пользователя опрятным образом, чтобы нельзя было не свой счет отправлять другим
    def __str__(self):
        # Чтобы не забыть что это значит:
        # Ищу все счета, связанные с id пользователя
        count = BankAccounts.objects.filter(user=self.user)
        number = list(count).index(self) + 1
        visible_part = self.account_number[:3] + '*' * (len(self.account_number) - 6) + self.account_number[-3:]
        return f"{number}. {visible_part} ({self.currency})"


# Таблица для переводов (можно сказать что и логирование переводов тоже)
class MoneyTransfer(models.Model):

    sender_id = models.ForeignKey(BankAccounts, related_name='transfers_sent', on_delete=models.CASCADE)
    source_account_number = models.CharField(max_length=20, blank=False, null=False, validators=[MinLengthValidator(16)])

    recipient_id = models.ForeignKey(BankAccounts, related_name='transfers_received', on_delete=models.CASCADE)
    destination_account_number = models.CharField(max_length=20, blank=False, null=False, validators=[MinLengthValidator(16)])

    # Пусть будет 7 цифр, а сумму огрничить в методе
    amount = models.DecimalField(max_digits=7, decimal_places=2, blank=False)
    converted_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=False)

    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.user.username} отправил {self.recipient.user.username}: {self.amount} {self.sender.currency}"

bankaccount/forms.py
from django import forms
from .models import *


# форма для создания счета
class CreateBankAccountForm(forms.ModelForm):
    class Meta:
        model = BankAccounts
        fields = ['account_type', 'balance', 'currency']
        # название в поле field должен совпадать с тем что снизу
        account_type = forms.ChoiceField(label='Тип счета', choices=BankAccounts.BankAccounts_TYPES)
        balance = forms.DecimalField(label='Баланс')
        currency = forms.ChoiceField(label='Валюта', choices=BankAccounts.Currency_TYPES)


class MoneyTransferForm(forms.ModelForm):
    class Meta:
        model = MoneyTransfer
        fields = ['sender_id', 'source_account_number', 'destination_account_number', 'amount']

    sender_id = forms.ModelChoiceField(
        label='Счет отправителя',
        queryset=BankAccounts.objects.none(),
        to_field_name='id',
    )
    source_account_number = forms.CharField(label='Счет отправителя', required=False )
    destination_account_number = forms.CharField(label='Счет получателя')
    amount = forms.DecimalField(label='Cумма отправки')

    confirmation_code = forms.CharField(label='Код подтверждения', required=False)

    def __init__(self, *args, user=None, **kwargs):
        super(MoneyTransferForm, self).__init__(*args, **kwargs)
        self.fields['sender_id'].queryset = BankAccounts.objects.filter(user=user)

bankaccount/views.py
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.utils import timezone
import random
import requests
from decimal import Decimal

from loans.models import Loan_History
from .models import *

# Create your views here.
from bankaccount.forms import *

menu = [
    # {'title': 'Личный кабинет', 'url_name': 'account_settings'},
    {'title': 'Просмотр счетов', 'url_name': 'bankaccount'},
    {'title': 'Денежные переводы', 'url_name': 'money_transfer'},
    {'title': 'Оформление кредита', 'url_name': 'apply_for_loan'},
    {'title': 'Платежи', 'url_name': 'payments'},
    {'title': 'История транзакций', 'url_name': 'money_transfer_history'},
]


# Банковский счет
def bankaccount_index(request):

    if request.method == 'POST':
        form = CreateBankAccountForm(request.POST)
        if form.is_valid():
            # для проверки баланса (тоже ставим ограничение)
            balance = form.cleaned_data['balance']

            # Сделаем лимит на количество создания счетов, чтобы нельзя было миллионов наделать
            account_type_name = form.cleaned_data['account_type']
            currency_type = form.cleaned_data['currency']

            # existing_accounts_count = BankAccounts.objects.filter(user=request.user, account_type=account_type_name).count()
            existing_accounts_count = BankAccounts.objects.filter(user=request.user, currency=currency_type).count()
            limit = 2
            # Нужно продумать про кредитный счет (скорее всего нужно убрать и сделать отдельно)

            if balance > 2000 or balance < 0:
                messages.error(request, 'Нельзя ввести сумму больше 2000s или меньше 0.')
            elif existing_accounts_count >= limit:
                # display_account_type = BankAccounts.ACCOUNT_TYPES_DICT.get(account_type_name, account_type_name)
                display_account_type = BankAccounts.CURRENCY_TYPES_DICT.get(currency_type, currency_type)
                messages.error(request, f'Вы достигли лимита создания счетов типа " { display_account_type }".')
            else:
                # Чтобы не забыть: сначала мы сохраняем данные карты а потом внешний ключ добавляем к записи
                bank_account = form.save(commit=False)
                bank_account.user = request.user
                bank_account.save()

                send_email_user_bankaccount(bank_account.account_number, bank_account.currency, request.user.email)

                messages.success(request, 'Счет успешно создан!')
                return redirect('bankaccount')

    else:
        form = CreateBankAccountForm()

    context = {
        'title': 'Банковские счета',
        'menu': menu,
        'form': form,
    }
    return render(request, 'bankaccount/Checking_BankAccount.html', context)


# Денежные переводы
def money_transfer_index(request):
    if request.method == 'POST':
        form = MoneyTransferForm(request.POST, user=request.user)

        if form.is_valid():
            print("Cleaned data:", form.cleaned_data)

            # получение оъекта
            source_account_number = form.cleaned_data['sender_id'].account_number
            destination_account_number = form.cleaned_data['destination_account_number']
            amount = form.cleaned_data['amount']

            # получение счетов отправителя и получателя , конвертаци я оъекта в строку
            source_account = BankAccounts.objects.get(account_number=str(source_account_number))
            fromCurrency = source_account.currency

            try:
                destination_account = BankAccounts.objects.get(account_number=destination_account_number)
            except BankAccounts.DoesNotExist:
                messages.error(request, 'Карточного счета с указанным номером не существует')
                return redirect('money_transfer')
            toCurrency = destination_account.currency

            converted_amount = convert_currency(amount, toCurrency, fromCurrency)

            if amount > 1000:

                if 'confirmation_code' in request.session:
                    confirmation_code = request.session['confirmation_code']
                else:
                    confirmation_code = ''.join(random.choices('0123456789', k=6))
                    # confirmation_code = '12345'
                    send_email_user(confirmation_code, request.user.email)

                request.session['confirmation_code'] = confirmation_code

                if 'request_new_code' in request.POST:
                    # Проверка времени последней отправки кода
                    user_last_confirmation_code_sent = request.user.last_confirmation_code_sent
                    if user_last_confirmation_code_sent and (
                            timezone.now() - user_last_confirmation_code_sent).seconds < 60:
                        messages.error(request, 'Вы можете запросить новый код только раз в минуту')
                        # return redirect('money_transfer')
                    else:
                        confirmation_code = generate_acception_code()
                        send_email_user(confirmation_code, request.user.email)

                        request.user.last_confirmation_code_sent = timezone.now()
                        request.user.save()

                        request.session['confirmation_code'] = confirmation_code

                        messages.success(request, 'Новый код подтверждения был отправлен на вашу почту')
                        # return redirect('money_transfer')

                if 'confirmation_code' in request.POST:
                    messages.info(request, 'Для продолжения операции вы должны вести код подтверждения, который присылается на вашу почту!')
                    user_confirmation_code = request.POST['confirmation_code']

                    if user_confirmation_code == confirmation_code:
                        transfer_operation(destination_account, source_account, amount, converted_amount, request)
                    else:
                        if user_confirmation_code.strip():
                            messages.error(request, 'Неверный код подтверждения')
                else:
                    messages.error(request, 'Введите код подтверждения')
            # чтобы просто видеть где меньше 1000
            else:
                transfer_operation(destination_account, source_account, amount, converted_amount, request)
        else:
            print("Form errors:", form.errors)
            messages.error(request, 'Вы ввели некорректные данные!')

    else:
        form = MoneyTransferForm(user=request.user)

    context = {
        'title': 'Денежные переводы',
        'menu': menu,
        'form': form,
    }
    return render(request, 'bankaccount/Money_Transfer.html', context)


def transfer_operation(destination_account, source_account, amount, converted_amount, request):
    if destination_account == source_account:
        messages.error(request, 'Вы не можете отправить на тот же счет средства!!!')
    elif source_account.balance >= amount:
        if amount >= 3:
            perform_transfer(source_account, destination_account, amount, converted_amount)
            messages.success(request, 'Перевод был успешно совершен')

            if 'confirmation_code' in request.session:
                del request.session['confirmation_code']

            return redirect('money_transfer')
        else:
            messages.error(request, 'Ошибка ввода сумму перевода!')
    else:
        messages.error(request, 'Недостаточно средств для перевода')


# def money_transfer_info(request):
#
#     if request.method == 'POST':
#         form = MoneyTransferForm(request.POST, user=request.user)
#
#         if form.is_valid():
#             destination_account_number = form.cleaned_data['destination_account_number']
#             try:
#                 destination_account = BankAccounts.objects.get(account_number=destination_account_number)
#                 username = destination_account.user_id.user.username
#                 context = {
#                     'title': 'Денежные переводы',
#                     'menu': menu,
#                     'form': form,
#                     'username': username,
#                 }
#                 return render(request, 'bankaccount/Money_Transfer.html', context)
#             except BankAccounts.DoesNotExist:
#                 messages.error(request, 'Карточного счета с указанным номером не существует')
#             return redirect('money_transfer')
#
#         context = {
#             'title': 'Денежные переводы',
#             'menu': menu,
#             'form': form,
#         }
#         return render(request, 'bankaccount/Money_Transfer.html', context)


def money_transfer_history(request):
    transfers = MoneyTransfer.objects.filter(sender_id__user=request.user)
    payments = Loan_History.objects.filter(loan_id__user=request.user)
    context = {
        'title': 'История транзакций',
        'menu': menu,
        'transfers': transfers,
        'payments': payments,
    }
    return render(request, 'bankaccount/money_transfer_history.html', context)


def send_email_user(confirmation_code, email):
    send_mail(
        'Код подтверждения перевода',
        f'Ваш код подтверждения: {confirmation_code}',
        'settings.EMAIL_HOST_USER',
        [email],
        fail_silently=False,
    )


def send_email_user_bankaccount(bankaccount, currency, email):
    subject = 'MyBank'
    message = (
        f'Уважаемый клиент, поздравляем вас с открытием нового счета в MyBank!\n'
        f'Ваш номер счета: {bankaccount} {currency}\n'
        f'Никому не сообщайте свой номер счета для обеспечения безопасности.\n\n'
        f'Вы можете войти в личный кабинет MyBank и управлять своим счетом.\n'
    )

    send_mail(
        subject,
        message,

bankaccount/templates/bankaccount/Checking_BankAccount.html
{% extends 'user/base_form.html' %}
{% load static %}

{% block content %}
<head>
    <link type="text/css" href="{% static 'bankaccount/css/create_account.css' %}" rel="stylesheet">
</head>

<header>
        <h1>Это страница вашего банковского счета</h1>
        <p>Здесь находятся ваши счета, {{ user.username }}!</p>
</header>

<br/>
<main class="block">

        {% if user.is_authenticated %}
<!--           <a href="{% url 'logout' %}">Logout</a>-->

        <div class="account-list">
        <h2>Ваши банковские счета:</h2>
        <table>
            <thead>
                <tr>
                    <th>Тип счета</th>
                    <th>Номер счета</th>
                    <th>Баланс</th>
                    <th>Валюта</th>
                    <th>Срок годности</th>
                </tr>
            </thead>
            <tbody>
                {% for account in user.bankaccounts_set.all %}
                    <tr>
                        <td>{{ account.get_account_type_display }}</td>
<!--                         <td>{{ account.account_number }}</td> -->
                        <td>{{ account.account_number|slice:":3" }}**********{{ account.account_number|slice:"-3:" }}</td>
                        <td>{{ account.balance }}</td>
                        <td>{{ account.get_currency_display }}</td>
                        <td>{{ account.expiration_date }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

        <div class="conic">
        <h2>Создать новый счет:</h2>
        <form method="post" action="{% url 'bankaccount' %}" class="column">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <p>Выберите тип счета:</p>
            {{ form.account_type }}

            <p>Выберите тип валюты:</p>
            {{ form.currency }}

            <p>Введите сумму депозита:</p>
            {{ form.balance }}
            
            <button type="submit">Создать счет</button>
        </form>
        </div>



        {% else %}
           <a href="{% url 'login' %}">Вход</a> |
           <a href="{% url 'registration' %}">Регистрация</a>
        {% endif %}

        </form>

</main>
{% endblock %}

bankaccount/templates/bankaccount/Money_Transfer.html
{% extends 'user/base_form.html' %}

{% load static %}

{% block content %}

<head>
        <link type="text/css" href="{% static 'bankaccount/css/money_transfer.css' %}" rel="stylesheet">
</head>

<header>
        <h1>Перевод денежных средств</h1>
        <p>Совершайте денежные переводы здесь, {{ user.username }}!</p>
</header>

<br/>
<main class="block">

        {% if user.is_authenticated %}
        <form method="post" action="{% url 'money_transfer' %}" class="block__form">

                {% csrf_token %}
                <div class="block">
                        <div class="block__card">
                            <div class="card">
                                        <div class="visa_logo">
                                            <img src="https://raw.githubusercontent.com/muhammederdem/credit-card-form/master/src/assets/images/visa.png" alt="">
                                        </div>
                                        <div class="visa_info">
                                            <img src="https://raw.githubusercontent.com/muhammederdem/credit-card-form/master/src/assets/images/chip.png" alt="">
                                            {{ form.sender_id }}
                                        </div>
                                        <div class="visa_crinfo">
                                            <p>02/12</p>
                                            <p>{{ user.surname}} {{ user.username }}</p>
                                        </div>
                            </div>
                        </div>
                </div>
        
                <div class="block">
                        <div class="block__card">
                            <div class="card">
                                        <div class="visa_logo">
                                            <img src="https://raw.githubusercontent.com/muhammederdem/credit-card-form/master/src/assets/images/visa.png" alt="">
                                        </div>
                                        <div class="visa_info">
                                            <img src="https://raw.githubusercontent.com/muhammederdem/credit-card-form/master/src/assets/images/chip.png" alt="">
                                            {{ form.destination_account_number }}
                                        </div>
                                        <div class="visa_crinfo">
                                            <p>02/12</p>

<!--                                                <button class="trigger">more info</button>-->

                                        </div>
                            </div>
                            <div class="form-group">
                            </div>
                        </div>
                </div>

                <div class="block__amount">
                        <p>Сумма перевода:</p>
                        {{ form.amount }}
                        <p>Код подтверждения при сумме больше 1000:</p>
                        {{ form.confirmation_code }}

                        <button type="submit" >Перевести</button>
                       <input type="submit" name="request_new_code" value="Запросить новый код">
                </div>
        
        </form>

        {% else %}
           <a href="{% url 'login' %}">Вход</a> |
           <a href="{% url 'registration' %}">Регистрация</a>
        {% endif %}

        </form>


</main>

<div class="modal">
    <div class="modal-content">
        <span class="close-button">×</span>
        <h1>User: В процессе доработки {{ username }}</h1>
    </div>
</div>

<script src="{% static 'bankaccount/js/modal.js' %}"></script>

{% endblock %}

bankaccount/templates/bankaccount/money_transfer_history.html
{% extends 'user/base_form.html' %}

{% load static %}

{% block content %}
<head>
    <link type="text/css" href="{% static 'bankaccount/css/create_account.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'bankaccount/css/money_transfer_history.css' %}" rel="stylesheet">
</head>
<header>
         <h1>{{ title }}</h1>
</header>

    <main class="main__block">
        <h2>История денежных переводов</h2>
        <div class="block__content">
            <table>
                <thead>
                    <tr>
                        <th>Имя отправителя</th>
                        <th>Отправитель</th>
                        <th>Имя получателя</th>
                        <th>Получатель</th>
                        <th>Сумма</th>
                        <th>Дата и время</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transfer in transfers %}
                        <tr>
                            <td>{{ transfer.sender_id.user.username }}</td>
                            <td>{{ transfer.source_account_number|slice:":3" }}**********{{ transfer.source_account_number|slice:"-3:" }}</td>
                            <td>{{ transfer.recipient_id.user.username }}</td>
                            <td>{{ transfer.destination_account_number |slice:":3" }}**********{{ transfer.destination_account_number|slice:"-3:" }}</td>
                            <td>{{ transfer.amount }} {{ transfer.sender_id.currency }}</td>
                            <td>{{ transfer.timestamp }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <h2>История платежей</h2>
        <div class="block__content">
            <table>
                <thead>
                    <tr>
                        <th>Плательщик</th>
                        <th>Операция</th>
                        <th>Номер кредитного счета</th>
                        <th>Сумма оплаты</th>
                        <th>Сумма задолженности</th>
                        <th>Валюта</th>
                        <th>Время операции</th>
                    </tr>
                </thead>
                <tbody>
                    {% for payment in payments %}
                        <tr>
                            <td>{{ user.username}}</td>
                            <td> оплата кредита </td>
                            <td>{{ payment.loan_number|slice:":3" }}**********{{ payment.loan_number|slice:"-3:" }}</td>
                            <td>{{ payment.summ_of_payment }}</td>
                            <td>{{ payment.remainder}}</td>
                            <td>{{ payment.currency }}</td>
                            <td>{{ payment.date_of_payment }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        

        
            
    </main>

{% endblock %}